CREATE DATABASE GOVERNMENT;

\c GOVERNMENT;

CREATE TYPE user_types ENUM ('admin', 'standart');

CREATE TABLE "User"(
   "Id" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
   "Name" VARCHAR(30) NOT NULL,
   "Login" VARCHAR(20) UNIQUE NOT NULL,
   "Password" VARCHAR(60) NOT NULL,
	"Type" user_types,
	"CreatedAt" TIMESTAMP NOT NULL DEFAULT NOW(),
	"UpdatedAt" TIMESTAMP NOT NULL DEFAULT NOW(),
   PRIMARY KEY("Id")
);


CREATE TABLE "Module"(
   "Id" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
   "Name" VARCHAR(20) UNIQUE NOT NULL,
   PRIMARY KEY("Id")
);

CREATE TYPE permission_types (1,2,3);

CREATE TABLE "User_Access"(
   "Fk_User" INTEGER NOT NULL REFERENCES "User"("Id"),
   "Fk_Module" INTEGER NOT NULL REFERENCES "Module"("Id"),
   "Permission" permission_types,
	"CreatedAt" TIMESTAMP NOT NULL DEFAULT NOW(),
	"UpdatedAt" TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE "FAQ"(
   "Id" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
   "Question" VARCHAR(60) UNIQUE NOT NULL,
   "Answer" VARCHAR(256) NOT NULL,
   "Order" SMALLINT NOT NULL, 
	"CreatedAt" TIMESTAMP NOT NULL DEFAULT NOW(),
	"UpdatedAt" TIMESTAMP NOT NULL DEFAULT NOW(),
   PRIMARY KEY("Id")
);

CREATE TABLE "Category"(
   "Id" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
   "Title" VARCHAR(50) UNIQUE NOT NULL,
   "Description" VARCHAR(50) NOT NULL,
	"CreatedAt" TIMESTAMP NOT NULL DEFAULT NOW(),
	"UpdatedAt" TIMESTAMP NOT NULL DEFAULT NOW(),
   PRIMARY KEY("Id")
);

CREATE TABLE "FAQ_Category"(
   "Fk_FAQ" INTEGER NOT NULL REFERENCES "FAQ"("Id"),
	"Fk_Category" INTEGER NOT NULL REFERENCES "Category"("Id"),
);
