CREATE DATABASE NEWSLETTER;

\c NEWSLETTER;

CREATE TABLE "News"(
    "Id_News" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    "Fk_Sender" INTEGER NOT NULL REFERENCES "Sender"("Id"),
    "Title" VARCHAR(50) UNIQUE NOT NULL,
    "Description" VARCHAR(50) NOT NULL,
    "Content" TEXT NOT NULL,
	"CreatedAt" TIMESTAMP NOT NULL DEFAULT NOW(),
	"UpdatedAt" TIMESTAMP NOT NULL DEFAULT NOW(),
    PRIMARY KEY("Id")
);

CREATE TABLE "Sender"(
    "Id" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    "Email" VARCHAR(64) UNIQUE NOT NULL,
    "Organ" VARCHAR(26) NOT NULL,
    "CreatedAt" TIMESTAMP NOT NULL DEFAULT NOW(),
    "UpdatedAt" TIMESTAMP NOT NULL DEFAULT NOW(),
    PRIMARY KEY("Id")
);

CREATE TABLE "Subscriber"(
    "Id" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    "Name" VARCHAR(26) NOT NULL,
    "Email" VARCHAR(64) UNIQUE NOT NULL,
	"CreatedAt" TIMESTAMP NOT NULL DEFAULT NOW(),
	"UpdatedAt" TIMESTAMP NOT NULL DEFAULT NOW(),
   PRIMARY KEY("Id")
);

--Pending
/*CREATE TABLE "Jobs"(
   "Id_News" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
   PRIMARY KEY("Id_News")
);*/
