FROM node:20-bullseye-slim as base
RUN apt-get update && apt-get install -y --no-install-recommends dumb-init
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build
RUN rm -rf node_modules

FROM node:20-bullseye-slim as development
WORKDIR /usr/src/app
LABEL mode="development"
COPY --from=base /usr/bin/dumb-init /usr/bin/dumb-init
COPY --from=base package*.json ./
ADD . .
RUN npm ci
ENV NODE_ENV development
EXPOSE 80
HEALTHCHECK --interval=30s --timeout=12s --start-period=30s \
  CMD node healthcheck.js
ENTRYPOINT ["dumb-init", "--"]
CMD [ "npm","run","debug:dev" ]

