version: '3'
services:
  postgres:
    image: postgis/postgis
    container_name: "seai-database"
    volumes:
      - ./db/ddl/equipments.sql:/docker-entrypoint-initdb.d/ddl-equipments.sql
      - ./db/seeds/equipments.sql:/docker-entrypoint-initdb.d/seeds-equipments.sql
      - ./db/ddl/government.sql:/docker-entrypoint-initdb.d/ddl-government.sql
      - ./db/ddl/management.sql:/docker-entrypoint-initdb.d/ddl-management.sql
      - ./db/ddl/newsletter.sql:/docker-entrypoint-initdb.d/ddl-newsletter.sql
      - ./db/ddl/logs.sql:/docker-entrypoint-initdb.d/ddl-logs.sql
      - ./db/ddl/census.sql:/docker-entrypoint-initdb.d/ddl-census.sql
    ports:
      - "5432:5432"
    env_file:
      - env_file
  # dev:
  #   image: "node:14.18.1-buster-slim"
  #   user: "node"
  #   working_dir: /home/node/dev
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - ./:/home/node/dev
