services:
  database:
    image: postgis/postgis:15-3.3-alpine
    container_name: "seai-database-dev"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./database/schemas:/docker-entrypoint-initdb.d
      - ./database/seeds:/usr/src/seeds
      - ./database/seed.sh:/usr/src/seed.sh
      - ./db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    restart: always
    networks:
      - custom
      - private

  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: development
    container_name: "seai-server"
    restart: always
    ports:
      - "127.0.0.1:${PORT}:80"
      - "127.0.0.1:9222:9222"
    volumes:
      - .:/usr/src/app
      - backend_node_modules:/usr/src/app/node_modules
    depends_on:
      database:
        condition: service_healthy
    networks:
      - custom
      - private

volumes:
  db-data: {}
  backend_node_modules: {}

# secrets:
#   db-password:
#     file: db/password.txt

networks:
  private:
  custom:
    name: jobs
    driver: bridge
