services:
  database:
    image: postgis/postgis:15-3.3-alpine
    container_name: "seai-database-dev"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./.docker/postgres/schemas:/docker-entrypoint-initdb.d
      - ./.docker/postgres/seeds:/usr/src/seeds
      - ./.docker/postgres/seed.sh:/usr/src/seed.sh
      - ./.docker/postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    restart: always
    networks:
      - custom
      - private

  backend:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        - API_PORT=${PORT}
    container_name: "seai-server"
    restart: always
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/usr/src/app
      - backend_node_modules:/usr/src/app/node_modules
    depends_on:
      database:
        condition: service_healthy
    networks:
      - custom
      - private

volumes:
  db-data: {}
  backend_node_modules: {}

networks:
  private:
  custom:
    name: jobs
    driver: bridge
