export * from "./user.routes";
export * from "./login.routes";
export * from "./faq.routes";
export * from "./census.routes";
export * from "./news.routes";
export * from "./equipments.routes";
export * from "./background-jobs.routes";
export * from "./access-key.routes";
export * from "./management/routes";
